### PR TITLE
Add  Neha Sharma

### PR DESCRIPTION
**Pull request by anoop-gupt**
added neha sharma - owner of Jslovers - speaker from Delhi NCR

### CODE REVIEW

**Comment by siddharthkp** [comment]
Do we have our consent for contacting for conferences? I don't know her github handle 😞

**Comment by anoop-gupt** [comment]
https://github.com/neha

**Comment by siddharthkp** [comment]
That's the coolest handle ever. @neha Can I update the consent column for you if you're okay with conference organisers to contact you?

**Comment by Neha** [comment]
Yes, sure

**Comment by siddharthkp** [comment]
Thanks!

**Pull request merged**
